# Arithmeatic operation

In [1]:
import  numpy as np

In [45]:
arr1 =  np.array([12,23,45,5006,776,79,21])

In [10]:
# min value
min =  np.min(arr1)
print("min",min)

# max value
max = np.max(arr1)
print("max",max)

min -1
max 5006


In [16]:
# for min element's argument
x =  np.argmin(arr1)
print(x)

# simalar for max element's index
y = np.argmax(arr1)
print(y)

6
3


In [47]:
# for n- array we can chose min and max acc to rows and col

arr2 =  np.array([[1,34,564,14],[456,8,6,100]])
#for  axis =0 => acc to row
x =  np.min(arr2,axis = 0) 
print(x)

x1 =  np.max(arr2,axis =0)
print(x1)

# for  axis =1 => acc to col
y =  np.min(arr2,axis = 1) 
print(y)

y1  = np.max(arr2,axis = 1)
print(y1)


[ 1  8  6 14]
[456  34 564 100]
[1 6]
[564 456]


In [37]:
# trigo functions

sin = np.sin(arr2)
print(sin)
print()
cos = np.cos(arr2)
print(cos)
print()
tan = np.tan(arr2)
print(tan)
print()
cot = np.reciprocal(tan)
print(cot)
print()
sec = np.reciprocal(np.cos(arr2))
print(sec)
print()
cosec = np.reciprocal(np.sin(arr2))
print(cosec)

[[ 0.84147098  0.52908269 -0.99646411 -0.84147098]
 [-0.45205268  0.98935825 -0.2794155  -0.50636564]]

[[ 0.54030231 -0.84857027  0.08401951  0.54030231]
 [-0.89199124 -0.14550003  0.96017029  0.86231887]]

[[  1.55740772  -0.62349896 -11.85991302  -1.55740772]
 [  0.50679049  -6.79971146  -0.29100619  -0.58721392]]

[[ 0.64209262 -1.60385191 -0.08431765 -0.64209262]
 [ 1.973202   -0.14706506 -3.436353   -1.70295692]]

[[ 1.85081572 -1.17845278 11.90199718  1.85081572]
 [-1.12108724 -6.87285064  1.04148193  1.15966382]]

[[ 1.18839511  1.89006374 -1.00354844 -1.18839511]
 [-2.21213158  1.01075622 -3.57889955 -1.97485753]]


In [40]:
# cumlative sum of the elements of array
csum = np.cumsum(arr2)
print(arr2)
print(csum) 


[[  1  34 564  -1]
 [456   8   6 100]]
[   1   35  599  598 1054 1062 1068 1168]


In [49]:
# square root func
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[ 3.46410162  4.79583152  6.70820393 70.75309181 27.85677655  8.88819442
  4.58257569]
[[ 1.          5.83095189 23.74868417  3.74165739]
 [21.3541565   2.82842712  2.44948974 10.        ]]
