Array

In [4]:
import numpy as np

x = [1,2,3,4]

# converting list in array

y = np.array(x)
print(y)
y

[1 2 3 4]


array([1, 2, 3, 4])

In [5]:
l = []
for i in range(1,11):
    int_ = int(input("Enter the elements"))
    l.append(int_)
arr1 = np.array(l)

print(arr1)

Enter the elements 45
Enter the elements 15
Enter the elements 55
Enter the elements 51
Enter the elements 514
Enter the elements 86
Enter the elements 64
Enter the elements 12
Enter the elements 33
Enter the elements 65


[ 45  15  55  51 514  86  64  12  33  65]


In [3]:
# Creating array with diifrent need and format

1 : Zeroes Array

In [6]:
import numpy as np
arr_zero = np.zeros(4)
print(arr_zero)
# <!-- it gives  1-D array -->
print()
#for 2-d array
ar_zero2 = np.zeros((3,4))
# <!-- (Row,Col) in the way -->
print(ar_zero2)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2 : One array

In [22]:
arr_one_1  = np.ones(5)
print(arr_one_1)
print()
arr_one_2 = np.ones((2,5))
print(arr_one_2)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3 : Empty Array

In [26]:
arr_emp_1 = np.empty(3)
print(arr_emp_1)
#it gives data of old array version or diffrent ans may be 

[1.31759166e-311 0.00000000e+000 4.94065646e-324]


4 : Range Array

In [34]:
arr_ran = np.arange(4,7,2)
print(arr_ran)
# similar to range function funcnality
# start with 0 end upto n-1 

#it will only generate 1-d array 
#  for 2-d array
# we use reshape()
arr_ran_2 = np.arange(12).reshape(4,3)
print(arr_ran_2)

# in we reshape we only give factors of theww size of the array in arange func()

[4 6]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


5 : Diagonal element(1) (Identity matrix)

In [38]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
arr_dia_rand = np.eye(3,5)
print(arr_dia_rand)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


6 : spaced interval array linspace()

In [42]:
arr_space = np.linspace(1,10,num=5)
print(arr_space)

[ 1.    3.25  5.5   7.75 10.  ]
