# Broadcasting in Array

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([11,24,57])

# print(arr1+arr2) 
#broadcasting error didnt have elements in two array

In [5]:
var1 = np.array([1,2,3])
print(var1.shape)
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)

print(var1+var2)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [9]:
var1 = np.array([[1],[2]])
var2 = np.array([[1,2,3],[4,5,6]])
print(var1.shape , var2.shape)

print(var1+var2)

(2, 1) (2, 3)
[[2 3 4]
 [6 7 8]]
