# Copy and view functions

In [1]:
import numpy as np

In [4]:
var1  = np.array([1,3,34,54])
cop1 = var1.copy()

print(var1)
print(cop1)

# afeect the original 
var1[0] =78
print(var1)
print(cop1)

[ 1  3 34 54]
[ 1  3 34 54]
[78  3 34 54]
[ 1  3 34 54]


In [5]:
x = np.array([897,456,75,51])
vie1  = x.view()

print(x)
print(vie1)

x[0] =78
print(x)
print(vie1)

[897 456  75  51]
[897 456  75  51]
[ 78 456  75  51]
[ 78 456  75  51]
