Array

In [3]:
import numpy as np

x = [1,2,3,4]

# converting list in array

y = np.array(x)
print(y)
y

[1 2 3 4]


array([1, 2, 3, 4])

In [9]:
l = []
for i in range(1,11):
    int_ = int(input("Enter the elements"))
    l.append(int_)

Enter the elements 45
Enter the elements 778
Enter the elements 45
Enter the elements 74
Enter the elements 41296
Enter the elements 45
Enter the elements 85
Enter the elements 963
Enter the elements 213
Enter the elements 78


In [10]:
arr1 = np.array(l)

print(arr1)

[   45   778    45    74 41296    45    85   963   213    78]


In [1]:
#  2-D arrays


In [3]:
import  numpy as np
arr2 =  np.array([[1,2,3,4,5],[1,232,45,23,21]])
print(arr2)
print(arr2.ndim)

[[  1   2   3   4   5]
 [  1 232  45  23  21]]
2


In [4]:
arr3 =   np.array([[[12,45,78],[23,45,79],[23,56,96]]])
print(arr3 , arr3.ndim)

[[[12 45 78]
  [23 45 79]
  [23 56 96]]] 3
