# Data Type

In [2]:
import numpy as np

In [9]:
var =  np.array([1,2,4,6347676742,43324156676,465789654678654])

print("Datatype" , var1.dtype)

Datatype int64


In [10]:
var1 =  np.array([1.456789,2.435678,4.321,6347676742,43324156676,465789654678654])

print("Datatype" , var1.dtype)

Datatype float64


In [11]:
var2  = np.array(["a","v","cv"])

print("Datatype" , var2.dtype)

Datatype <U2


In [13]:
var2  = np.array(["A","V","CV",1,32,34,4,5,6,7,78])

print("Datatype" , var2.dtype)

Datatype <U21


Data conversion in array:

In [16]:
# method  1
x =  np.array([1,2,34,554,67543,12])
print("Data type:" ,x.dtype)
print(x)
# i want to change in data type int8 by this way
x =  np.array([1,2,34,554,67543,12],dtype = np.float64)
print("Data type:" ,x.dtype)
print(x)

Data type: int64
[    1     2    34   554 67543    12]
Data type: float64
[1.0000e+00 2.0000e+00 3.4000e+01 5.5400e+02 6.7543e+04 1.2000e+01]


In [18]:
#method -2  by func way():

x =  np.array([1,2,34,554,67543,12])

new  = np.float32(x)
print("Data type old:" ,x.dtype)
print("Data type new:" ,new.dtype)

print(x)
print(new)

Data type old: int64
Data type new: float32
[    1     2    34   554 67543    12]
[1.0000e+00 2.0000e+00 3.4000e+01 5.5400e+02 6.7543e+04 1.2000e+01]
