# Indexing

In [2]:
import numpy as np

In [3]:
var1 = np.array([1,34,57,98])
                #(0,1 ,2 ,3))
                #(-4,-3,-2,-1)
print(var1[3])
print(var1[-2])

98
57


In [16]:
# for 2-d array
var2 = np.array([[9,8,3],[4,5,6]])

print(var2.ndim)
print()
print(var2[0,1]) # for 8(row,col)

# for 3-d array

var3 = np.array([[[1,2],[1,2]] ,[[3,2],[4,5]]])
print(var3.ndim)
print()
print(var3[0,1,0])#last 2 in 2nd array 
print(var3[1,0,0])#3 from 2nd row array

2

8
3

1
3


# Silicing

In [20]:
var4 = np.array([12,846,97,46,347,76])
print(var4)
print(var4.ndim)

[ 12 846  97  46 347  76]
1


In [47]:
print("846 to 46->",var4[1:4])
print("97 to end->",var4[2:])
print("12 to 46->",var4[:4])
print("one one jump ->",var4[::1])
print("one one jump ->",var4[::-1]) #reverse the array
print("some patteren ->",var4[2:6:2])
print(var4[-3:-1])
print("-ve slicing->",var4[-4:3])

846 to 46-> [846  97  46]
97 to end-> [ 97  46 347  76]
12 to 46-> [ 12 846  97  46]
one one jump -> [ 12 846  97  46 347  76]
one one jump -> [ 76 347  46  97 846  12]
some patteren -> [ 97 347]
[ 46 347]
-ve slicing-> [97]


In [32]:
var5 = np.array([[45,79,43,21],[134,94,35,309],[54,79,5,6]])

print(var5.ndim)

2


In [40]:
print("2nd row 94 to 309->",var5[1,1:4])
print(var5[0:3,2]) #(all 3 row return index 2 from all )
print(var5[0:3:2, 1:4])

2nd row 94 to 309-> [ 94  35 309]
[43 35  5]
[[79 43 21]
 [79  5  6]]
