# Joining And Spiliting 

In [2]:
import numpy as np

In [4]:
var1 = np.array([18,24,65,90])
var2 = np.array([34,75,56,31])

arr1  = np.concatenate((var1,var2))
print(arr1)

[18 24 65 90 34 75 56 31]


In [5]:
x = np.array([[18,24,32],[65,234,90]])
y = np.array([[34,75,56],[745,31,31]])

arr  = np.concatenate((x,y),axis=0)
print(arr)
print()
arr1  = np.concatenate((x,y),axis=1)
print(arr1)

[[ 18  24  32]
 [ 65 234  90]
 [ 34  75  56]
 [745  31  31]]

[[ 18  24  32  34  75  56]
 [ 65 234  90 745  31  31]]


In [6]:
# using stack 
arr  = np.stack((x,y),axis=0)
print(arr)
print()
arr1  = np.stack((x,y),axis=1)
print(arr1)
print()
arr2  = np.stack((x,y),axis=2)
print(arr1)

[[[ 18  24  32]
  [ 65 234  90]]

 [[ 34  75  56]
  [745  31  31]]]

[[[ 18  24  32]
  [ 34  75  56]]

 [[ 65 234  90]
  [745  31  31]]]

[[[ 18  24  32]
  [ 34  75  56]]

 [[ 65 234  90]
  [745  31  31]]]


In [11]:
# stack Along the row merge
arr  = np.hstack((x,y))
print(arr)
print()

# stack Along the col merge
arr1  = np.vstack((x,y))
print(arr1)
print()

# stack Along the height merge
arr2  = np.dstack((x,y))
print(arr2)
print()

[[ 18  24  32  34  75  56]
 [ 65 234  90 745  31  31]]

[[ 18  24  32]
 [ 65 234  90]
 [ 34  75  56]
 [745  31  31]]

[[[ 18  34]
  [ 24  75]
  [ 32  56]]

 [[ 65 745]
  [234  31]
  [ 90  31]]]



In [12]:
# split Array

In [17]:
a1 = np.array([12,345,653,87,2,34])

newarr = np.array_split(a1,3)
print(newarr)

print(type(newarr))#it is list of array

print(newarr[1]) 

[array([ 12, 345]), array([653,  87]), array([ 2, 34])]
<class 'list'>
[653  87]


In [31]:
#for 2-d split

a2 = np.array([[12,345],[653,87],[2,34]])

new = np.array_split(a2,6)
print(new)
print(new[2])
print()
new = np.array_split(a2,2)
print(new)
print(new[1])

[array([[ 12, 345]]), array([[653,  87]]), array([[ 2, 34]]), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64), array([], shape=(0, 2), dtype=int64)]
[[ 2 34]]

[array([[ 12, 345],
       [653,  87]]), array([[ 2, 34]])]
[[ 2 34]]


In [37]:
#along with axis 

a3= np.array([[12,345],[653,87],[2,34]])

new = np.array_split(a3,2,axis=0)#along row
print(new)
print()
new = np.array_split(a3,3,axis=0)#along row
print(new)
print()
new = np.array_split(a3,2,axis=1)#along col
print(new)

[array([[ 12, 345],
       [653,  87]]), array([[ 2, 34]])]

[array([[ 12, 345]]), array([[653,  87]]), array([[ 2, 34]])]

[array([[ 12],
       [653],
       [  2]]), array([[345],
       [ 87],
       [ 34]]), array([], shape=(3, 0), dtype=int64)]
