# Arithmeatic operation

In [15]:
import  numpy as np

In [4]:
x =  np.array([12,23,45,56,776,79])

ADD

In [5]:
xadd =  x+3 
# for single number 
print(xadd)

[ 15  26  48  59 779  82]


In [12]:
# addition of 1- d array
var1 = np.array([463,7896,78,63,94,65])
var1 =  np.add(var1,x)
print(var1)

[ 475 7919  123  119  870  144]


SUB

In [18]:
xsub=  x-3 
# for single number 
print(xsub)

# subtrcation of 1- d array
var1 = np.array([463,7896,78,63,94,65])
var2 =  np.subtract(var1,x)
print(var2)


[  9  20  42  53 773  76]
[ 451 7873   33    7 -682  -14]


DIVIDE

In [20]:
xdiv =  x/3 
# for single number 
print(xdiv)

# divide of 1- d array
var1 = np.array([463,7896,78,63,94,65])
new =  np.divide(var1,x)
print(new)


[  4.           7.66666667  15.          18.66666667 258.66666667
  26.33333333]
[3.85833333e+01 3.43304348e+02 1.73333333e+00 1.12500000e+00
 1.21134021e-01 8.22784810e-01]


Mod

In [21]:
xmod =  x%3 
# for single number 
print(xmod)

# modulus of 1- d array
var1 = np.array([463,7896,78,63,94,65])
new =  np.mod(var1,x)
print(new)

[0 2 0 2 2 1]
[ 7  7 33  7 94 65]


Multiply

In [23]:
xmul =  x*3 
# for single number 
print(xmul)

# Multiply of 1- d array
var1 = np.array([463,7896,78,63,94,65])
new =  np.multiply(var1,x)
print(new)

[  36   69  135  168 2328  237]
[  5556 181608   3510   3528  72944   5135]


Reciprocal 

In [26]:
# Multiply of 1- d array
var1 = np.array([4.63,78.96,0.78,0.63,92.4,45.65])
new =  np.reciprocal (var1)
print(new)

[0.21598272 0.01266464 1.28205128 1.58730159 0.01082251 0.02190581]


# For 2-d Array

In [39]:
var2 = np.array([[1,23],[4578,63]])
var3 = np.array([[1,2],[1,6]])

# For addition
new =  np.add(var2,var3)
print(new)
# it follows the matrix addition rule in this...


# For Multiplication
new =  np.multiply(var2,var3)
print(new)
# it  does not follows the matrix Multiplication rule in this...

# for actual matrix dot product (two mnatrix Multiplication )
new =  var2 @ var3
print(new)

[[   2   25]
 [4579   69]]
[[   1   46]
 [4578  378]]
[[  24  140]
 [4641 9534]]
