# Matrix

In [1]:
import numpy as np

In [7]:
var1 = np.matrix([[1,2,3],[2,45,67]])

print(var1)
print(var1.ndim)
print(type(var1))

[[ 1  2  3]
 [ 2 45 67]]
2
<class 'numpy.matrix'>


In [6]:
var2 = np.array([[1,2,3],[2,45,67]])
print(var2)
print(var2.ndim)
print(type(var2))

[[ 1  2  3]
 [ 2 45 67]]
2
<class 'numpy.ndarray'>


In [26]:
var2 = np.array([[1,2,3],[2,45,67],[79,16,63]])
var3  = np.array([[2,3,4],[6,7,8],[16,67,34]])

# add
print(var2+var3)

# sub
print(var2-var3)

# mul by matrix rule
print(var2 @ var3)
print(var2.dot(var3))
print(var2 * var3) #it is diffrent 

#div
print(var2 / var3)
print(var3 /var2)

[[ 3  5  7]
 [ 8 52 75]
 [95 83 97]]
[[ -1  -1  -1]
 [ -4  38  59]
 [ 63 -51  29]]
[[  62  218  122]
 [1346 4810 2646]
 [1262 4570 2586]]
[[  62  218  122]
 [1346 4810 2646]
 [1262 4570 2586]]
[[   2    6   12]
 [  12  315  536]
 [1264 1072 2142]]
[[0.5        0.66666667 0.75      ]
 [0.33333333 6.42857143 8.375     ]
 [4.9375     0.23880597 1.85294118]]
[[2.         1.5        1.33333333]
 [3.         0.15555556 0.11940299]
 [0.20253165 4.1875     0.53968254]]


# Inbulit functions of matrix

In [27]:
# transpose matrix 

var4 = np.matrix([[1,23,34],[65,97,65]])
print(var4)

print(np.transpose(var4))
print(var4.T) #same work

[[ 1 23 34]
 [65 97 65]]
[[ 1 65]
 [23 97]
 [34 65]]
[[ 1 65]
 [23 97]
 [34 65]]


In [30]:
# swap axes 
print(np.swapaxes(var4,0,1))

var5 = np.matrix([[1,23],[65,97]])
print(var5)
print()
print(np.swapaxes(var5,0,1))


[[ 1 65]
 [23 97]
 [34 65]]
[[ 1 23]
 [65 97]]

[[ 1 65]
 [23 97]]


In [31]:
# inverse matrix

print(np.linalg.inv(var5))

[[-0.06938484  0.01645207]
 [ 0.04649499 -0.00071531]]


In [34]:
# power of matrix
print(np.linalg.matrix_power(var5,4))
print()
print(np.linalg.matrix_power(var5,0))
print()
print(np.linalg.matrix_power(var5,-2))

# determinate of matrix

print(np.linalg.det(var5))

[[ 16595996  27949600]
 [ 78988000 133255196]]

[[1 0]
 [0 1]]

[[ 0.00557919 -0.00115329]
 [-0.00325931  0.00076545]]
-1398.0
