# Random number

In [18]:
import numpy as np

1 Rand()

In [4]:
ran = np.random.rand(4)
print(ran)

[0.59549434 0.23349789 0.55418653 0.05452114]


In [7]:
# for 2-d arrays
ran = np.random.rand(2,5)
print(ran)

[[0.93502251 0.84459056 0.680431   0.1518847  0.96896926]
 [0.64684587 0.06043926 0.0935927  0.31967536 0.49893731]]


2 Randn()

In [13]:
ran2 = np.random.randn(5)
print(ran2)

[-1.09462301  0.05313036  1.54972741  1.18111685  2.17834615]


In [14]:
ran3 = np.random.randn(5,7,3)
print(ran3)

[[[ 3.21778642 -0.61155318 -1.38944048]
  [-0.79425243  0.96644127 -2.331027  ]
  [-1.69427079 -1.79639388 -1.25002012]
  [-0.44866056 -2.0793548  -0.58857094]
  [-0.7691839  -0.16281191 -1.68825112]
  [ 2.31671973 -0.23105722  0.85476225]
  [ 0.83185012 -0.24484558 -2.01990723]]

 [[ 0.65221592 -1.26101822  0.79070599]
  [-0.69297151 -0.67779421 -0.52885114]
  [-0.49408415  1.26497144 -1.81129801]
  [ 1.07368983 -1.29439058  1.8787574 ]
  [-0.66292213  0.93488405 -1.12790721]
  [ 1.0022039   1.22851326  0.75435892]
  [ 1.64703375  1.54797306 -1.59162837]]

 [[ 0.69092576 -1.39558749  1.08462253]
  [ 0.13335413  0.62737604 -0.43847975]
  [ 0.10706956 -0.02783017  0.56566224]
  [ 0.0420238  -1.57580788 -0.56274043]
  [-2.94119665  0.69254801  0.37106847]
  [-1.42238639 -1.52654888  0.08735934]
  [ 1.0582914  -0.06312313  0.82276356]]

 [[ 0.77724048  0.48595279 -0.27799644]
  [ 1.06123758 -1.74539461  0.3981142 ]
  [-1.21712731 -0.17167619 -0.7260372 ]
  [-2.21701858 -1.75969092  0.7428

 3 Randf()

In [26]:
import numpy as np
ra3 = np.random.ranf(7)
print(ra3)

print()
ra3 = np.random.ranf((2,3))
print(ra3)

[0.60286058 0.3899787  0.38841938 0.45199348 0.48619531 0.57801524
 0.09726451]

[[0.18527168 0.53009025 0.85404344]
 [0.25612605 0.24541694 0.58570815]]


4 randint()

In [35]:
# varr = np.random.randint(min,max,total_number)
# default arguments  start =0 and step =1

ran4 = np.random.randint(5,20,10)
print(ran4)

[16 15 12 13 19 18 17 12  5 11]
