# shaping of Array

In [10]:
import numpy as np

x = np.array([[1,2,43,87,94],[563,584,78,94,45]])


In [11]:
print(x.shape)

(2, 5)


In [13]:
y = np.array([1,32,54,76],ndmin =5)
print(y)
print(y.shape)

[[[[[ 1 32 54 76]]]]]
(1, 1, 1, 1, 4)


# Reshape of Array

In [26]:
arr2  = np.array([1,2,45,78,9,5,12,21,43,45,6,7])
print(arr2)
print(arr2.ndim)
print()

new  =  arr2.reshape(2,3,2) 
# we check new dimens 
print(new.ndim)
# 2 row and  3col elements arrange
print(new)

[ 1  2 45 78  9  5 12 21 43 45  6  7]
1

3
[[[ 1  2]
  [45 78]
  [ 9  5]]

 [[12 21]
  [43 45]
  [ 6  7]]]


In [32]:
#  again going back to n-d to 1-d array back
new1  = new.reshape(-1)
print(new1)
print(new1.ndim)

[ 1  2 45 78  9  5 12 21 43 45  6  7]
1
