# Numpy Special Functions

In [8]:
import numpy as np 

In [7]:
# Search in array

var1 =  np.array([12,78,46,123,75,65,12,74,46,89,46])
x = np.where(var1 == 46)
print(x)

# some operation in where

y = np.where(var1%2 == 0)
print(y)

(array([ 2,  8, 10]),)
(array([ 0,  1,  2,  6,  7,  8, 10]),)


In [17]:
#  Search sorted array

var2 = np.array([1, 9, 12, 23, 34, 45, 56, 67, 78, 90])

x1 = np.searchsorted(var2,46)
print(x1)

y1 = np.searchsorted(var2,[6,123,23],side='left')
print(y1)

6
[ 1 10  3]


In [22]:
# sorting of array

var3 =  np.array([12,78,46,123,75,65,12,74,46,89,46])
print(np.sort(var3))


var4 = np.array(['q','A','cv','E','HG'])
print(np.sort(var4))

var5 = np.array([[45, 12, 78, 23, 9],[56, 34, 67, 1, 90]])
print(np.sort(var5))

[ 12  12  46  46  46  65  74  75  78  89 123]
['A' 'E' 'HG' 'cv' 'q']
[[ 9 12 23 45 78]
 [ 1 34 56 67 90]]


In [25]:
# Filter Array 

var4 = np.array([[2, 7, 4, 9, 6,47,19],[11, 8, 15, 10, 13,78,94]])

new = var4[var4%2 == 0]
print(new)

[ 2  4  6  8 10 78 94]


# Arithematic functions special one

In [34]:
# shuffle

var5 = np.array([1,2,3,54,66])
np.random.shuffle(var5)
print(var5)

[ 1  3 54  2 66]


In [38]:
# unique

var6 = np.array([12,78,46,123,75,65,12,74,46,89,46])
uni = np.unique(var6,return_index = True)
print(uni)

uni_1 = np.unique(var6,return_index = True,return_counts = True)
print(uni_1)

(array([ 12,  46,  65,  74,  75,  78,  89, 123]), array([0, 2, 5, 7, 4, 1, 9, 3]))
(array([ 12,  46,  65,  74,  75,  78,  89, 123]), array([0, 2, 5, 7, 4, 1, 9, 3]), array([2, 3, 1, 1, 1, 1, 1, 1]))


In [45]:
# Resize 

var7 = np.array([1,788,54,2781,342,34])
y = np.resize(var7,(4,2))
print(y)

[[   1  788]
 [  54 2781]
 [ 342   34]
 [   1  788]]


In [48]:
#  Flatten 

print(y.flatten())

# order in paramter

print(y.flatten(order = 'F')) #col wise
print(y.flatten(order = 'a'))
print(y.flatten(order = 'K'))

[   1  788   54 2781  342   34    1  788]
[   1   54  342    1  788 2781   34  788]
[   1  788   54 2781  342   34    1  788]
[   1  788   54 2781  342   34    1  788]


In [52]:
#  Ravel 

print("Ravel",np.ravel(y,order='K'))

Ravel [   1  788   54 2781  342   34    1  788]


#  Insert And Delete Numpy array func

In [57]:
var_1 = np.array([12,34,65,146,79])

print(var_1)
print(var_1.ndim)
print(type(var_1))
print(var_1.dtype)

[ 12  34  65 146  79]
1
<class 'numpy.ndarray'>
int64


In [60]:
v = np.insert(var_1,2,274)
print(v)

# for multiple index
v = np.insert(var_1,(2,5,4),274)
print(v)

[ 12  34 274  65 146  79]
[ 12  34 274  65 146 274  79 274]


In [67]:
arr1 = np.array([[ 12,34,274,65,146,274],[12,78,46,123,75,65,]])

new_1 = np.insert(arr1,2,6,axis=0)
print(new_1)

new_1 = np.insert(arr1,(4,5),4,axis=1)
print(new_1)

new_1 = np.insert(arr1,2,[62,434,123,654,6,3],axis=0)
print(new_1)


[[ 12  34 274  65 146 274]
 [ 12  78  46 123  75  65]
 [  6   6   6   6   6   6]]
[[ 12  34 274  65   4 146   4 274]
 [ 12  78  46 123   4  75   4  65]]
[[ 12  34 274  65 146 274]
 [ 12  78  46 123  75  65]
 [ 62 434 123 654   6   3]]


In [76]:
# using append func

new2 = np.append(arr1,[[23],[34]],axis=1)
print(new2)

new2 = np.append(arr1,[[23,34,797,45,5,641]],axis=0)
print(new2)

[[ 12  34 274  65 146 274  23]
 [ 12  78  46 123  75  65  34]]
[[ 12  34 274  65 146 274]
 [ 12  78  46 123  75  65]
 [ 23  34 797  45   5 641]]


In [77]:
# Delete 

var_1 = np.array([12,34,65,146,79])
d = np.delete(var_1,1)
print(d)

[ 12  65 146  79]


In [79]:
# for 2-d arrays delete

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

new_arr = np.delete(arr, 1, axis=0)
print(new_arr)

new_arr = np.delete(arr, 1, axis=1)
print(new_arr)

new_arr = np.delete(arr, [0, 2], axis=0)
print(new_arr)

new_arr = np.delete(arr, [0, 2], axis=1)
print(new_arr)

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
[[4 5 6]]
[[2]
 [5]
 [8]]
